config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/homes/about" => "homes#about", as: "about"
  
  resources :users, only: [:index, :show]
  resources :books, only: [:new, :show, :create, :index, :edit, ]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
 belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
      
  has_many :book, dependent: :destroy  
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
 
 def after_sign_in_path_for(resource)
    users_path
  end
  
  def after_sign_out_path_for(resource)
    top_path
  end
 
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.User_id = current_user.id
    @book.save
    redirect_to books_path
  end
  
  def index
    @books = Book.all
  end
  
  def show
    @book = Book.find(book_params[:id])
  end
  
  def edit
    @book = Book.find(book_params[:id])
  end
  
  def destroy
    @book = Book.find(book_params[:id])
  end
  
  
  
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
 end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def index
    @users = User.all
    @user = User.find(user[:id])
  end

  def show
    @user = User.find(user[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new book.html.erb
<div>
  <h1>User info</h1>
  <%= image_tag user.get_image %>
  <p>name  <%= user.name %>  </p>
  <p>introduction <%= user.introduction %> </p>


<h1>New book</h1>
  <%= form_with model: book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :shop_name %>
    <h4>Option</h4>
      <%= f.text_area :caption %></br>
    <%= f.submit ' Create Book ' %>
  <% end %>

</div>

app/views/books/edit.html.erb
<body>
  <div>
  <%= flash[:notice] %>
</div>

 <div id="error_explanation">
  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved
   <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
   </ul>
  <% end %>
 </div>

<h1>Editing Book</h1>

<%= form_with model: @book, url:update_book_path(@book.id), method: :patch do |f| %>

<div class = "field">
 <label for = "book_body">Title</label>
  <%= f.text_field :title %>
</div>

<div class = "field">
 <label for = "book_body">Body</label>
  <%= f.text_area :body %>
</div>  
  
<div class = "submit">
  <%= f.submit ' Update Book ' %>
</div>

  <%= link_to "Show", book_path(@book.id) %>
  <%= link_to "Back",:books %>
    
<% end %>


  
</body>

app/views/books/index.html.erb
<% @books.each do |book| %>

<div>
  <%= image_tag 'sample-author1.jpg' %>
  <h4>Title</h4>
   <%= list.title %>
  <h4>Option</h4>
   <%= list.body %>
  
</div>

<% end %>

app/views/books/new.html.erb
<h1>New book</h1>
  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :shop_name %>
    <h4>Option</h4>
      <%= f.text_area :caption %></br>
    <%= f.submit ' Create Book ' %>
  <% end %>
  

app/views/books/show.html.erb
<body>
  <h1>Book detail</h1>
  <%= image_tag user.get_image %>
  <%= user.name %> 
  
  <p><strong>Title:</strong><%= @book.title %></p>

  <p><strong>Body:</strong><%= @book.body %></p>

  <%= link_to "Edit", edit_book_path(@book.id) %>
  <%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure？" %>

</body>

app/views/homes/about.html.erb
<h1>Aboutページ</h1>

<body>
  <header></header>
  <main>Welcome to <strong>Bookers!</strong></main>
  <fotter></fotter>
</body>

app/views/homes/top.html.erb
<body>

  <main>
    <h1>welcome to <storong>Bookers</storong>!!</h1>

    <P>In <storong>Bookers</storong>,</P>
    <P>you can share and exchange your opinions , inpressions ,</P>
    <P>and emotions</P>

    <P>about various books!</P>
    
  </main>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadaisan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
        <li>
          <%= link_to "Bookers", root_path %>
        </li>
        <li>
          <%= link_to "Home", users_path %>
        </li>
      <% if user_signed_in? %>
        <li>
          <%= link_to 'New book', users_path %>
        </li>
        <li>
          <%= link_to "Log out", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "About", about_path %>
        </li>
        <li>
          <%= link_to "Sign up", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "Log in", new_user_session_path %>
        </li>
     <% end %>
    </header>
    <%= yield %>
    <main>
    </main>
    <fotter>CopyRight Infratop.inc</fotter>
  </body>
    
</html>

app/views/users/index.html.erb
  <%= render 'new book', user: @user , book: @book %>
  
  <div>
    <h1>User info</h1>
    <%= image_tag @user.get_image %>
    <p>name  <%= @user.name %>  </p>
    <p>introduction <%= @user.introduction %> </p>
  </div>

app/views/users/show.html.erb
<% @users.each do |user| %>
  <div>
    <h1>Users</h1>
    <%= image_tag user.get_image %>
    <p>name  <%= user.name %>  </p>
    <p><%= link_to "show" user_path(user.id) %> </p>
  </div>
<% end %>